### PR TITLE
Loader + game version combo search field

### PR DESCRIPTION
**Pull request by stairman06**
Required backend implementation for https://github.com/modrinth/knossos/issues/447.

My SQL might be poor so feel free to critique.

### CODE REVIEW

**Review by Geometrically — CHANGES_REQUESTED** [review]
why not just use the existing joins for this?

**Comment by stairman06** [comment]
I don't believe this is possible with the existing joins? They don't have the right association between version and game version/loader. But I'll need to check and look at it again.

**Comment by Geometrically** [comment]
couldn't you only join the combos and then extract the rest of the versions and loaders in the rust side of code?

**Comment by stairman06** [comment]
I think with that we'd end up with the loader ID and the game version ID, which aren't what we want. To actually convert those to the loader name and game version name we have to ask the database AFAIK. But maybe I'm misunderstanding?

**Comment by Geometrically** [comment]
Superseded by #731

**Pull request closed without merging**
