### PR TITLE
Add description field to category

### PR DESCRIPTION
**Pull request by bluebear94**
See modrinth/knossos#1166.

### CODE REVIEW

**Comment by bluebear94** [comment]
Actually, it might be a better idea to store the descriptions in the Knossos codebase. Should I close this PR?

**Comment by HyperSoop** [comment]
No, I think if categories come from Labirinth it makes sence for their descriptions to be in the same place

**Comment by triphora** [comment]
Considering internationalization, it makes more sense for it to be on the frontend

**Comment by HyperSoop** [comment]
Ohh right then yeah

**Comment by bluebear94** [comment]
Alright, I’ll close this PR and implement this feature on the frontend.

**Pull request closed without merging**
