### PR TITLE
fix/ci: Fix build matrix

### PR DESCRIPTION
**Pull request by Redblueflame**

### CODE REVIEW

**Comment by Redblueflame** [comment]
Done !

**Comment by cfanoulis** [comment]
...when will I ever get authorization to merge to master LMFAO

**Comment by Redblueflame** [comment]
I can't too, until all checks passes

**Comment by cfanoulis** [comment]
just noticed I can do that whoops

**Comment by Redblueflame** [comment]
@cfanoulis Just added permissions for anyone in the backend team :wink:

**Comment by cfanoulis** [comment]
still no perms lmao

**Comment by Redblueflame** [comment]
concern

**Pull request merged**
