### PR TITLE
Basic public webhook

### PR DESCRIPTION
**Pull request by stairman06**
Right now there is some duplicate code between the moderation and public webhooks, ideally I want to add other features like loaders and authors to the public webhook but that requires SQL queries AFAIK. 

This also changes from using image to thumbnail in the embed, it works better for mod icons.

### CODE REVIEW

**Review by wafflecoffee — APPROVED** [review]

**Comment by Geometrically** [comment]
Holding off on merging this, will have to work out the details of a channel and how we want to implement it.

**Comment by wafflecoffee** [comment]
Would it be possible to change this to look similar to Hermes, just adapted for projects instead of versions?

**Comment by Prospector** [comment]
Or rather, like the rewrite's embeds. The project type is included in the title, and the environment information isn't really that important until you click on the mod. All it really needs is the summary.

image

**Comment by venashial** [comment]
Here's my take on the embed format ([and accompanying source](https://share.discohook.app/go/ekxu71m8)).
Screenshot 2022-07-27 at 11 37 30 PM

**Comment by ZeoNight** [comment]
> Here's my take on the embed format ([and accompanying source](https://share.discohook.app/go/ekxu71m8)). Screenshot 2022-07-27 at 11 37 30 PM

Cannot seem to access the discohook link

**Comment by triphora** [comment]
Superseded by #492

**Pull request closed without merging**
