### PR TITLE
remove Fabric 'source file' validation

### PR DESCRIPTION
**Pull request by Jamalam360**
discussed on discord

### CODE REVIEW

**Comment by Jamalam360** [comment]
side note: `ValidationResult::Warning` seems like something that shouldn't prevent publishing. On the frontend it's displayed as a red error box

**Comment by ThatGravyBoat** [comment]
Is there a reason why this is only being removed for fabric and not all loaders?

**Comment by Geometrically** [comment]
we don't do this on other loaders

**Comment by ThatGravyBoat** [comment]
@Geometrically 
> we don't do this on other loaders

You do it in every other mod loader:
https://github.com/modrinth/labrinth/blob/master/src/validate/forge.rs#L39
https://github.com/modrinth/labrinth/blob/master/src/validate/forge.rs#L90
https://github.com/modrinth/labrinth/blob/master/src/validate/quilt.rs#L38 (This one is actually a 1:1 of the fabric check)

**Comment by lukebemish** [comment]
The forge validator is particularly insidious; a forge mod need not have a mods.toml file to be valid, even on new versions!

**Pull request merged**
