### PR TITLE
Never return an empty 404 response

### PR DESCRIPTION
**Pull request by wafflecoffee**

### CODE REVIEW

**Comment by Geometrically** [comment]
is this change needed? what's wrong with the current system?

**Comment by wafflecoffee** [comment]
It was breaking Minotaur sometimes because of how Java deals with null stuff - if a project can't be found, it would throw a completely unrelated error because ErrorInfo was null.

It's also inconsistent with how nonexistent routes send a 404 with a body (example https://api.modrinth.com/v2/thisisafakeroute), but (for example) nonexistent projects don't have a body at all (example https://api.modrinth.com/v2/project/thisisafakeproject).

**Comment by jamierocks** [comment]
Given that the documentation is clear that 404 responses don't have a response body, I don't particularly think this is neccasery either. I'm on the fence as to whether I would consider this a breaking change.

**Comment by Geometrically** [comment]
Agreed, I know it's inconsistent with errors but this could break other tools. Maybe something for v3?

**Comment by wafflecoffee** [comment]
Sounds good

**Comment by jamierocks** [comment]
Standardising the error responses would be nice for v3! Don't forget the 400 Bad Requests :)

**Pull request closed without merging**
